name: Generate Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get repo content
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Snake SVG for both light and dark mode
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: wintwah243
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif

      # Push the generated files to the output branch
      - name: Push GitHub Pages content
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
