name: Generate Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate light mode Snake
      - name: Generate Snake Light Mode
        uses: Platane/snk@v3
        with:
          github_user_name: wintwah243
          outputs: dist/snake.svg,dist/snake.gif
          dark_mode: false

      # Generate dark mode Snake
      - name: Generate Snake Dark Mode
        uses: Platane/snk@v3
        with:
          github_user_name: wintwah243
          outputs: dist/snake-dark.svg,dist/snake-dark.gif
          dark_mode: true

      # Push generated files to the output branch
      - name: Push GitHub Pages content
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
